### ISSUE TITLE
finish docs, cleanup, finalize

### ISSUE THREAD

**Issue by jonaswjs** [LaxarJS/laxar-developer-tools-content#3]
- [ ]  use stable dependencies
- [ ] finish docs (README)
- [ ] add to travis 
- [ ] add var to .gitignore
